version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: masjid-backend
    expose:
      - "8000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/sql.db
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masjid-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
